event_inherited();
volume = 15;
calories = 15;
price = 8*15;
is_pill = true;
script_use = pill_diet;
sfx = LIQUID;
uses = 20;
name = "Pill Diet Bottle";
desc = "Decrease digestion speed by 50% (stackable)";