function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // ControlDialogue
	global.__objectDepths[1] = 0; // ControlEnv
	global.__objectDepths[2] = 1; // DragPanel
	global.__objectDepths[3] = 0; // Girl
	global.__objectDepths[4] = 0; // ButtonSound
	global.__objectDepths[5] = 0; // ButtonStartCleanse
	global.__objectDepths[6] = 0; // btCheck
	global.__objectDepths[7] = 1; // TubeBack
	global.__objectDepths[8] = 0; // Control
	global.__objectDepths[9] = 0; // ControlSquad
	global.__objectDepths[10] = 0; // ControlMission
	global.__objectDepths[11] = 0; // ControlSelect
	global.__objectDepths[12] = 0; // ControlSelectBuild
	global.__objectDepths[13] = 2; // ControlBattle
	global.__objectDepths[14] = 0; // ControlDrop
	global.__objectDepths[15] = 0; // ControlInventory
	global.__objectDepths[16] = 0; // ControlUpgrade
	global.__objectDepths[17] = 0; // ControlInfo
	global.__objectDepths[18] = 0; // ControlLevelUp
	global.__objectDepths[19] = 0; // ControlTutorial
	global.__objectDepths[20] = 1; // ControlCleanse
	global.__objectDepths[21] = 1; // ControlPressure
	global.__objectDepths[22] = 0; // Card
	global.__objectDepths[23] = 0; // CardButton
	global.__objectDepths[24] = 0; // CardBuild
	global.__objectDepths[25] = 0; // ButtonBack
	global.__objectDepths[26] = 0; // ButtonDeploy
	global.__objectDepths[27] = 0; // MockMissionButton
	global.__objectDepths[28] = 0; // ButtonRetreat
	global.__objectDepths[29] = -1000; // DialogueOk
	global.__objectDepths[30] = 0; // ButtonSkipD
	global.__objectDepths[31] = -1000; // DialogueYesNo
	global.__objectDepths[32] = -1000000; // Cursor
	global.__objectDepths[33] = -100; // EffectStat
	global.__objectDepths[34] = 0; // ButtonScroll
	global.__objectDepths[35] = -2; // EffectWeapon
	global.__objectDepths[36] = -100000; // Gate
	global.__objectDepths[37] = 0; // CardPlaceholder
	global.__objectDepths[38] = 0; // ButtonStage
	global.__objectDepths[39] = 0; // ButtonSquad
	global.__objectDepths[40] = 0; // ButtonHelp
	global.__objectDepths[41] = 0; // BtMCompletion
	global.__objectDepths[42] = 0; // GirlHolder
	global.__objectDepths[43] = -1; // ToolRubCard
	global.__objectDepths[44] = 0; // CardMonster
	global.__objectDepths[45] = 0; // MPretzel
	global.__objectDepths[46] = 0; // MCookie
	global.__objectDepths[47] = 0; // MChickenDrum
	global.__objectDepths[48] = 0; // MChickenDrumS
	global.__objectDepths[49] = 0; // MChickenWhole
	global.__objectDepths[50] = 0; // MChickenWholeS
	global.__objectDepths[51] = 0; // MSushi
	global.__objectDepths[52] = 0; // MShrimp
	global.__objectDepths[53] = 0; // MFishFilet
	global.__objectDepths[54] = 0; // MFishFried
	global.__objectDepths[55] = 0; // MOrange
	global.__objectDepths[56] = 0; // MStrawberry
	global.__objectDepths[57] = 0; // MLemon
	global.__objectDepths[58] = 0; // MMelon
	global.__objectDepths[59] = 0; // MWaterMelon
	global.__objectDepths[60] = 0; // MApple
	global.__objectDepths[61] = 0; // MPotato
	global.__objectDepths[62] = 0; // MEggplant
	global.__objectDepths[63] = 0; // MOlive
	global.__objectDepths[64] = 0; // MOnion
	global.__objectDepths[65] = 0; // MBacon
	global.__objectDepths[66] = 0; // MCakeSlice
	global.__objectDepths[67] = 0; // MChilli
	global.__objectDepths[68] = 0; // Item2
	global.__objectDepths[69] = 0; // ItemCredit
	global.__objectDepths[70] = 0; // CardItem
	global.__objectDepths[71] = 0; // TubeMouth
	global.__objectDepths[72] = -1; // Squad
	global.__objectDepths[73] = 0; // CheckPoint
	global.__objectDepths[74] = 0; // PatientHolder
	global.__objectDepths[75] = 0; // FChickenDrum
	global.__objectDepths[76] = 0; // FPie
	global.__objectDepths[77] = 0; // FBacon
	global.__objectDepths[78] = 0; // FFriedEggs
	global.__objectDepths[79] = 0; // FStrawberry
	global.__objectDepths[80] = 0; // FCookie
	global.__objectDepths[81] = 0; // FPretzel
	global.__objectDepths[82] = 0; // FRoastedChicken
	global.__objectDepths[83] = 0; // FWatermelon
	global.__objectDepths[84] = 1; // OptionLabels
	global.__objectDepths[85] = 0; // Blockage
	global.__objectDepths[86] = 0; // Patient
	global.__objectDepths[87] = 0; // Sophie
	global.__objectDepths[88] = 0; // Fork
	global.__objectDepths[89] = 0; // PatientCard
	global.__objectDepths[90] = 0; // ControlMenu
	global.__objectDepths[91] = 0; // Table
	global.__objectDepths[92] = 0; // Food
	global.__objectDepths[93] = 0; // ToolRub
	global.__objectDepths[94] = 0; // MenuItem
	global.__objectDepths[95] = 0; // ToolEar2
	global.__objectDepths[96] = 1; // Trash
	global.__objectDepths[97] = 0; // MenuCard
	global.__objectDepths[98] = 0; // ButtonFinish
	global.__objectDepths[99] = 0; // DelayMaker
	global.__objectDepths[100] = 0; // ButtonMusic
	global.__objectDepths[101] = 0; // ControlProfile
	global.__objectDepths[102] = 0; // ConrtrolSessionComplete
	global.__objectDepths[103] = 1; // ControlStats
	global.__objectDepths[104] = 0; // Wipe
	global.__objectDepths[105] = 0; // Smear
	global.__objectDepths[106] = 0; // ControlSetting
	global.__objectDepths[107] = 0; // ButtonDialogue
	global.__objectDepths[108] = 0; // ControlMain
	global.__objectDepths[109] = 1; // ControlClinic
	global.__objectDepths[110] = -200; // Button
	global.__objectDepths[111] = 0; // ButtonNavi
	global.__objectDepths[112] = 0; // Interactive
	global.__objectDepths[113] = 0; // UIComponent
	global.__objectDepths[114] = -2; // ButtonSleep
	global.__objectDepths[115] = -1; // Button10min
	global.__objectDepths[116] = -1; // Button30Min
	global.__objectDepths[117] = -1; // ButtonMap
	global.__objectDepths[118] = -1; // ButtonJournal
	global.__objectDepths[119] = -1; // ButtonBackpack
	global.__objectDepths[120] = 1; // ContactCard
	global.__objectDepths[121] = 2; // PhoneBack
	global.__objectDepths[122] = 0; // TaskNote
	global.__objectDepths[123] = 3; // ButtonStat
	global.__objectDepths[124] = 3; // ButtonAbilities
	global.__objectDepths[125] = 0; // ButtonInfo
	global.__objectDepths[126] = 0; // ButtonAbility
	global.__objectDepths[127] = 0; // ControlJournal
	global.__objectDepths[128] = 0; // ControlBackpack
	global.__objectDepths[129] = 0; // ControLGeneralStore
	global.__objectDepths[130] = 0; // ControlAbilities
	global.__objectDepths[131] = 0; // ControlInteract
	global.__objectDepths[132] = 0; // Scaling
	global.__objectDepths[133] = 0; // Window
	global.__objectDepths[134] = -20; // BuyWindow
	global.__objectDepths[135] = -20; // ItemWindow
	global.__objectDepths[136] = 0; // Stat
	global.__objectDepths[137] = 0; // ContentHidden
	global.__objectDepths[138] = 0; // DropZone
	global.__objectDepths[139] = 0; // Bubble
	global.__objectDepths[140] = -100000; // obj_textbox
	global.__objectDepths[141] = 0; // oDropDown
	global.__objectDepths[142] = -1; // dropdown_dialogue
	global.__objectDepths[143] = -1; // dropdown_music
	global.__objectDepths[144] = 0; // oDropDownTester
	global.__objectDepths[145] = 0; // BtHumanitiesB
	global.__objectDepths[146] = 0; // BtDormitoriesB
	global.__objectDepths[147] = 0; // BtScienceB
	global.__objectDepths[148] = 0; // BtPark
	global.__objectDepths[149] = 0; // BtStoreB
	global.__objectDepths[150] = 0; // BtFastFood
	global.__objectDepths[151] = 0; // BtToCity
	global.__objectDepths[152] = 0; // BtToUni
	global.__objectDepths[153] = 0; // BtBeach
	global.__objectDepths[154] = 0; // BtGymB
	global.__objectDepths[155] = 0; // BTSalon
	global.__objectDepths[156] = 0; // BtBambiRanch
	global.__objectDepths[157] = 0; // BTAliceApartment
	global.__objectDepths[158] = 0; // BtCafeteria
	global.__objectDepths[159] = 0; // BtLibrary
	global.__objectDepths[160] = 0; // Item
	global.__objectDepths[161] = 0; // ItemCard
	global.__objectDepths[162] = 0; // IAir
	global.__objectDepths[163] = 0; // IEnergyDrink
	global.__objectDepths[164] = 0; // IApple
	global.__objectDepths[165] = 0; // IStrawberry
	global.__objectDepths[166] = 0; // IShrimps
	global.__objectDepths[167] = 0; // IOrange
	global.__objectDepths[168] = 0; // ICakeSlice
	global.__objectDepths[169] = 0; // IPump
	global.__objectDepths[170] = 0; // Character
	global.__objectDepths[171] = 0; // CharacterHolder
	global.__objectDepths[172] = -1; // PlayerHolder
	global.__objectDepths[173] = 0; // Alice
	global.__objectDepths[174] = 0; // Amber
	global.__objectDepths[175] = 0; // Bria
	global.__objectDepths[176] = 0; // Anna
	global.__objectDepths[177] = 0; // Bambi
	global.__objectDepths[178] = 0; // Sabrina
	global.__objectDepths[179] = 0; // Player
	global.__objectDepths[180] = 0; // NPC
	global.__objectDepths[181] = 0; // Librarian
	global.__objectDepths[182] = 0; // GymAssistant
	global.__objectDepths[183] = 0; // Manicurist
	global.__objectDepths[184] = 0; // FastFoodWorker
	global.__objectDepths[185] = 0; // Trigger
	global.__objectDepths[186] = 0; // T_Anna_Goodnight
	global.__objectDepths[187] = 0;//FatbucksCashier

	global.__objectNames[0] = "ControlDialogue";
	global.__objectNames[1] = "ControlEnv";
	global.__objectNames[2] = "DragPanel";
	global.__objectNames[3] = "Girl";
	global.__objectNames[4] = "ButtonSound";
	global.__objectNames[5] = "ButtonStartCleanse";
	global.__objectNames[6] = "btCheck";
	global.__objectNames[7] = "TubeBack";
	global.__objectNames[8] = "Control";
	global.__objectNames[9] = "ControlSquad";
	global.__objectNames[10] = "ControlMission";
	global.__objectNames[11] = "ControlSelect";
	global.__objectNames[12] = "ControlSelectBuild";
	global.__objectNames[13] = "ControlBattle";
	global.__objectNames[14] = "ControlDrop";
	global.__objectNames[15] = "ControlInventory";
	global.__objectNames[16] = "ControlUpgrade";
	global.__objectNames[17] = "ControlInfo";
	global.__objectNames[18] = "ControlLevelUp";
	global.__objectNames[19] = "ControlTutorial";
	global.__objectNames[20] = "ControlCleanse";
	global.__objectNames[21] = "ControlPressure";
	global.__objectNames[22] = "Card";
	global.__objectNames[23] = "CardButton";
	global.__objectNames[24] = "CardBuild";
	global.__objectNames[25] = "ButtonBack";
	global.__objectNames[26] = "ButtonDeploy";
	global.__objectNames[27] = "MockMissionButton";
	global.__objectNames[28] = "ButtonRetreat";
	global.__objectNames[29] = "DialogueOk";
	global.__objectNames[30] = "ButtonSkipD";
	global.__objectNames[31] = "DialogueYesNo";
	global.__objectNames[32] = "Cursor";
	global.__objectNames[33] = "EffectStat";
	global.__objectNames[34] = "ButtonScroll";
	global.__objectNames[35] = "EffectWeapon";
	global.__objectNames[36] = "Gate";
	global.__objectNames[37] = "CardPlaceholder";
	global.__objectNames[38] = "ButtonStage";
	global.__objectNames[39] = "ButtonSquad";
	global.__objectNames[40] = "ButtonHelp";
	global.__objectNames[41] = "BtMCompletion";
	global.__objectNames[42] = "GirlHolder";
	global.__objectNames[43] = "ToolRubCard";
	global.__objectNames[44] = "CardMonster";
	global.__objectNames[45] = "MPretzel";
	global.__objectNames[46] = "MCookie";
	global.__objectNames[47] = "MChickenDrum";
	global.__objectNames[48] = "MChickenDrumS";
	global.__objectNames[49] = "MChickenWhole";
	global.__objectNames[50] = "MChickenWholeS";
	global.__objectNames[51] = "MSushi";
	global.__objectNames[52] = "MShrimp";
	global.__objectNames[53] = "MFishFilet";
	global.__objectNames[54] = "MFishFried";
	global.__objectNames[55] = "MOrange";
	global.__objectNames[56] = "MStrawberry";
	global.__objectNames[57] = "MLemon";
	global.__objectNames[58] = "MMelon";
	global.__objectNames[59] = "MWaterMelon";
	global.__objectNames[60] = "MApple";
	global.__objectNames[61] = "MPotato";
	global.__objectNames[62] = "MEggplant";
	global.__objectNames[63] = "MOlive";
	global.__objectNames[64] = "MOnion";
	global.__objectNames[65] = "MBacon";
	global.__objectNames[66] = "MCakeSlice";
	global.__objectNames[67] = "MChilli";
	global.__objectNames[68] = "Item2";
	global.__objectNames[69] = "ItemCredit";
	global.__objectNames[70] = "CardItem";
	global.__objectNames[71] = "TubeMouth";
	global.__objectNames[72] = "Squad";
	global.__objectNames[73] = "CheckPoint";
	global.__objectNames[74] = "PatientHolder";
	global.__objectNames[75] = "FChickenDrum";
	global.__objectNames[76] = "FPie";
	global.__objectNames[77] = "FBacon";
	global.__objectNames[78] = "FFriedEggs";
	global.__objectNames[79] = "FStrawberry";
	global.__objectNames[80] = "FCookie";
	global.__objectNames[81] = "FPretzel";
	global.__objectNames[82] = "FRoastedChicken";
	global.__objectNames[83] = "FWatermelon";
	global.__objectNames[84] = "OptionLabels";
	global.__objectNames[85] = "Blockage";
	global.__objectNames[86] = "Patient";
	global.__objectNames[87] = "Sophie";
	global.__objectNames[88] = "Fork";
	global.__objectNames[89] = "PatientCard";
	global.__objectNames[90] = "ControlMenu";
	global.__objectNames[91] = "Table";
	global.__objectNames[92] = "Food";
	global.__objectNames[93] = "ToolRub";
	global.__objectNames[94] = "MenuItem";
	global.__objectNames[95] = "ToolEar2";
	global.__objectNames[96] = "Trash";
	global.__objectNames[97] = "MenuCard";
	global.__objectNames[98] = "ButtonFinish";
	global.__objectNames[99] = "DelayMaker";
	global.__objectNames[100] = "ButtonMusic";
	global.__objectNames[101] = "ControlProfile";
	global.__objectNames[102] = "ConrtrolSessionComplete";
	global.__objectNames[103] = "ControlStats";
	global.__objectNames[104] = "Wipe";
	global.__objectNames[105] = "Smear";
	global.__objectNames[106] = "ControlSetting";
	global.__objectNames[107] = "ButtonDialogue";
	global.__objectNames[108] = "ControlMain";
	global.__objectNames[109] = "ControlClinic";
	global.__objectNames[110] = "Button";
	global.__objectNames[111] = "ButtonNavi";
	global.__objectNames[112] = "Interactive";
	global.__objectNames[113] = "UIComponent";
	global.__objectNames[114] = "ButtonSleep";
	global.__objectNames[115] = "Button10min";
	global.__objectNames[116] = "Button30Min";
	global.__objectNames[117] = "ButtonMap";
	global.__objectNames[118] = "ButtonJournal";
	global.__objectNames[119] = "ButtonBackpack";
	global.__objectNames[120] = "ContactCard";
	global.__objectNames[121] = "PhoneBack";
	global.__objectNames[122] = "TaskNote";
	global.__objectNames[123] = "ButtonStat";
	global.__objectNames[124] = "ButtonAbilities";
	global.__objectNames[125] = "ButtonInfo";
	global.__objectNames[126] = "ButtonAbility";
	global.__objectNames[127] = "ControlJournal";
	global.__objectNames[128] = "ControlBackpack";
	global.__objectNames[129] = "ControLGeneralStore";
	global.__objectNames[130] = "ControlAbilities";
	global.__objectNames[131] = "ControlInteract";
	global.__objectNames[132] = "Scaling";
	global.__objectNames[133] = "Window";
	global.__objectNames[134] = "BuyWindow";
	global.__objectNames[135] = "ItemWindow";
	global.__objectNames[136] = "Stat";
	global.__objectNames[137] = "ContentHidden";
	global.__objectNames[138] = "DropZone";
	global.__objectNames[139] = "Bubble";
	global.__objectNames[140] = "obj_textbox";
	global.__objectNames[141] = "oDropDown";
	global.__objectNames[142] = "dropdown_dialogue";
	global.__objectNames[143] = "dropdown_music";
	global.__objectNames[144] = "oDropDownTester";
	global.__objectNames[145] = "BtHumanitiesB";
	global.__objectNames[146] = "BtDormitoriesB";
	global.__objectNames[147] = "BtScienceB";
	global.__objectNames[148] = "BtPark";
	global.__objectNames[149] = "BtStoreB";
	global.__objectNames[150] = "BtFastFood";
	global.__objectNames[151] = "BtToCity";
	global.__objectNames[152] = "BtToUni";
	global.__objectNames[153] = "BtBeach";
	global.__objectNames[154] = "BtGymB";
	global.__objectNames[155] = "BTSalon";
	global.__objectNames[156] = "BtBambiRanch";
	global.__objectNames[157] = "BTAliceApartment";
	global.__objectNames[158] = "BtCafeteria";
	global.__objectNames[159] = "BtLibrary";
	global.__objectNames[160] = "Item";
	global.__objectNames[161] = "ItemCard";
	global.__objectNames[162] = "IAir";
	global.__objectNames[163] = "IEnergyDrink";
	global.__objectNames[164] = "IApple";
	global.__objectNames[165] = "IStrawberry";
	global.__objectNames[166] = "IShrimps";
	global.__objectNames[167] = "IOrange";
	global.__objectNames[168] = "ICakeSlice";
	global.__objectNames[169] = "IPump";
	global.__objectNames[170] = "Character";
	global.__objectNames[171] = "CharacterHolder";
	global.__objectNames[172] = "PlayerHolder";
	global.__objectNames[173] = "Alice";
	global.__objectNames[174] = "Amber";
	global.__objectNames[175] = "Bria";
	global.__objectNames[176] = "Anna";
	global.__objectNames[177] = "Bambi";
	global.__objectNames[178] = "Sabrina";
	global.__objectNames[179] = "Player";
	global.__objectNames[180] = "NPC";
	global.__objectNames[181] = "Librarian";
	global.__objectNames[182] = "GymAssistant";
	global.__objectNames[183] = "Manicurist";
	global.__objectNames[184] = "FastFoodWorker";
	global.__objectNames[185] = "Trigger";
	global.__objectNames[186] = "T_Anna_Goodnight";
	global.__objectNames[187] = "FatbucksCashier";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
